linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/CodexForgeBR/cli-tools

run:
  timeout: 5m
